### ISSUE TITLE
Too many sessions running

### ISSUE THREAD

**Issue by Jagohu** [tchellomello/python-ring-doorbell#230]
Hi,

I have an issue which came up with all the releases, including the last one - it seems like every time I call the script it creates a new instance, which ultimately "floods" my android app out of the Ring account.
I run it through a crontab every 10 minutes.
![image](https://user-images.githubusercontent.com/35196588/103103391-082d8c80-4621-11eb-9aa0-4949db812cff.png)

Any idea how to fix this? I thought with the last version (0.6.2) it'd be solved.
Thanks!

**Comment by riptidewave93** [comment]
@Jagohu This should have been fixed in PR https://github.com/tchellomello/python-ring-doorbell/pull/228, which isn't in any release yet.

**Comment by tchellomello** [comment]
Closed by #228

**Comment by Jagohu** [comment]
I still have the same issue with 0.7.0. What am I missing?
![image](https://user-images.githubusercontent.com/35196588/107113587-2c0b0180-6860-11eb-86f0-ea5de5910a6d.png)
